import React from "react";
const TodosContext = React.createContext({
    id: 1,
    title: '',
    description: '',
    dueDate: '',
    todos: [],
    addTodo: () => {},
    removeTodo: () => {},
    setTitle: () => {},
    setDescription: () => {},
    setId: () => {},
    setDueDate: () => {},
    cartIsShown: '',
    showCartHandler: () => {},
    hideCartHandler: () => {},
    titleIsTouched: () => {},
    descriptionIsTouched: () => {},
    dueDateIsTouched: () => {},
    resetTitle: () => {},
    resetDescription: () => {},
    resetDueDate: () => {},
    titleHasError: () => {},
    dueDateHasError: () => {},
    descriptionHasError: () => {},
    titleIsValid: () => {},
    dueDateIsValid: () => {},
    descriptionIsValid: () => {},
    defaultTodoState: [],
    todoReducer: () => {},
    setTodo: () => {}
});
export default TodosContext;